@echo off
echo Cleaning node_modules...
rmdir /s /q node_modules
echo Installing all dependencies...
call npm install
echo Installing dev dependencies...
call npm install --save-dev typescript @types/react @types/node @types/react-dom eslint eslint-config-next
echo Done.
